/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Ejercicio4;
import javax.swing.JOptionPane;

/**
 *
 * @author DanielWilfredo
 */
public class FrmEjerc4 extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjerc4
     */
    public FrmEjerc4() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblcod1.setVisible(false);
        lblcod2.setVisible(false);
        lblcod3.setVisible(false);
        lblcod4.setVisible(false);
    }
     Ejercicio4 ejer4 = new Ejercicio4();
      int numeConta=0;
    String pin="";

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        lblcod1 = new javax.swing.JLabel();
        lblcod2 = new javax.swing.JLabel();
        lblcod4 = new javax.swing.JLabel();
        lblcod3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Codigo Celular");
        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        btn3.setBorder(null);
        btn3.setContentAreaFilled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        btn4.setBorder(null);
        btn4.setContentAreaFilled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.png"))); // NOI18N
        btn5.setBorder(null);
        btn5.setContentAreaFilled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        btn6.setBorder(null);
        btn6.setContentAreaFilled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N
        btn7.setBorder(null);
        btn7.setContentAreaFilled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N
        btn.setBorder(null);
        btn.setContentAreaFilled(false);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/9.png"))); // NOI18N
        btn9.setBorder(null);
        btn9.setContentAreaFilled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/0.png"))); // NOI18N
        btn0.setBorder(null);
        btn0.setContentAreaFilled(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese su pin:");

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        btn1.setBorder(null);
        btn1.setContentAreaFilled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        btn2.setBorder(null);
        btn2.setContentAreaFilled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        lblcod1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigoo.png"))); // NOI18N

        lblcod2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigoo.png"))); // NOI18N

        lblcod4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigoo.png"))); // NOI18N

        lblcod3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigoo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn))
                                    .addComponent(btn0))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn9))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcod1)
                                .addGap(2, 2, 2)
                                .addComponent(lblcod2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(lblcod3)
                                .addGap(2, 2, 2)
                                .addComponent(lblcod4)))
                        .addGap(8, 8, 8)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcod3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcod2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcod4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcod1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn2)
                    .addComponent(btn3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn5)
                    .addComponent(btn4)
                    .addComponent(btn6))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn9)
                    .addComponent(btn7)
                    .addComponent(btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn0)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 4;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                 JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";
                  
                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
 if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 1;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                 JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
         if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 0;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
           if(this.ejer4.getPin().equals(pin))
                {
                    JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte(); 
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
    if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 7;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                     JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 2;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                   JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
      if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 3;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                    if(this.ejer4.getPin().equals(pin))
                {
                JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                      pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
      if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 5;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                   JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 6;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                 JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }

    }//GEN-LAST:event_btn6ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
     if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 8;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
             JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                   pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btnActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
      if(this.ejer4.getNumeInte()>= 1)
        {
            numeConta += 1;
            pin += 9;
            switch (numeConta) {
                    case 1:
                         lblcod1.setVisible(true);
                    break;
                    case 2:
                         lblcod2.setVisible(true);
                    break;
                    case 3:
                         lblcod3.setVisible(true);
                    break;
                    case 4:
                         lblcod4.setVisible(true);
                    break;
                default:
                    
            }
            if(numeConta == 4)
            {
                if(this.ejer4.getPin().equals(pin))
                {
                    JOptionPane.showMessageDialog(this, "Pin correcto");
                    numeConta =0;
                    pin= "";

                }
                else
                {
                    int res = this.ejer4.getNumeInte();
                    res = res -1;
                    JOptionPane.showMessageDialog(this, "Pin incorrecto le quedan: " + res + " intentos");
                    numeConta =0;
                    pin= "";             
                    this.ejer4.setNumeInte(res);
                    lblcod1.setVisible(false);
                    lblcod2.setVisible(false);
                    lblcod3.setVisible(false);
                    lblcod4.setVisible(false);
                }
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Aplicacion Bloqueada, cierri y vuelva a abrir para intentar nuevamente");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjerc4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjerc4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcod1;
    private javax.swing.JLabel lblcod2;
    private javax.swing.JLabel lblcod3;
    private javax.swing.JLabel lblcod4;
    // End of variables declaration//GEN-END:variables
}
