/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Ejercicio1;

/**
 *
 * @author DanielWilfredo
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        btnEjercicio1 = new javax.swing.JMenu();
        btnEjercicio2 = new javax.swing.JMenu();
        btnEjercicio3 = new javax.swing.JMenu();
        btnEjercicio4 = new javax.swing.JMenu();
        btnEje5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia ejercicios 2 ::: Wilfredo Granados ");

        btnEjercicio1.setText("Ejercicio 1");
        btnEjercicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjercicio1MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjercicio1);

        btnEjercicio2.setText("Ejercicio 2");
        btnEjercicio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjercicio2MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjercicio2);

        btnEjercicio3.setText("Ejercicio 3");
        jMenuBar1.add(btnEjercicio3);

        btnEjercicio4.setText("Ejercicio 4");
        btnEjercicio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjercicio4MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjercicio4);

        btnEje5.setText("Ejercicio5");
        btnEje5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEje5MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEje5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjercicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjercicio1MouseClicked
  FrmEjerc1 mostrar = new FrmEjerc1();
       mostrar.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnEjercicio1MouseClicked

    private void btnEjercicio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjercicio2MouseClicked
FrmEjerc2 mostra2 = new FrmEjerc2();
mostra2.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnEjercicio2MouseClicked

    private void btnEjercicio4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjercicio4MouseClicked
        FrmEjerc4 eje4 = new FrmEjerc4();
        eje4.setVisible(true);
    }//GEN-LAST:event_btnEjercicio4MouseClicked

    private void btnEje5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEje5MouseClicked
FrmEjerc5 ejer5 = new FrmEjerc5();
ejer5.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnEje5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnEje5;
    private javax.swing.JMenu btnEjercicio1;
    private javax.swing.JMenu btnEjercicio2;
    private javax.swing.JMenu btnEjercicio3;
    private javax.swing.JMenu btnEjercicio4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
